-- Create post_media table for media carousel functionality
-- Structure matches product_media but for blog posts

CREATE TABLE IF NOT EXISTS post_media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES blog_post(id) ON UPDATE CASCADE ON DELETE CASCADE,
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name TEXT NULL,
  description TEXT NULL,
  "order" INTEGER NULL DEFAULT 1,
  is_video BOOLEAN NULL DEFAULT FALSE,
  
  -- Video fields
  video_url TEXT NULL,
  video_player TEXT NULL,
  
  -- Image fields
  image_url TEXT NULL,
  thumbnail_url TEXT NULL,
  
  -- Attribution and metadata (for Unsplash, etc.)
  attrs JSONB NULL,
  
  -- Order constraint
  CONSTRAINT post_media_order_check CHECK ("order" >= 0)
);

-- Indexes for better performance
CREATE INDEX IF NOT EXISTS idx_post_media_post_id ON post_media USING BTREE (post_id);
CREATE INDEX IF NOT EXISTS idx_post_media_organization_id ON post_media USING BTREE (organization_id);

-- Enable RLS
ALTER TABLE post_media ENABLE ROW LEVEL SECURITY;

-- RLS Policies - Allow public read access
CREATE POLICY "Public can view post media"
  ON post_media
  FOR SELECT
  USING (true);

-- RLS Policies - Authenticated users can manage their organization's post media
CREATE POLICY "Authenticated users can insert post media"
  ON post_media
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update post media"
  ON post_media
  FOR UPDATE
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can delete post media"
  ON post_media
  FOR DELETE
  TO authenticated
  USING (true);

-- Add comment
COMMENT ON TABLE post_media IS 'Media carousel items for blog posts (images and videos), structure matches product_media';
