-- Migration: Restructure website_templatesectionheading table
-- Date: 2025-11-27
-- Description: Consolidate fields into JSONB structure (content, translations, style)

-- Step 1: Create backup table
CREATE TABLE IF NOT EXISTS website_templatesectionheading_backup AS 
SELECT * FROM public.website_templatesectionheading;

-- Step 2: Add new JSONB columns
ALTER TABLE public.website_templatesectionheading
ADD COLUMN IF NOT EXISTS content jsonb DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS translations jsonb DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS style jsonb DEFAULT '{}'::jsonb;

-- Step 3: Migrate data to new structure
UPDATE public.website_templatesectionheading
SET 
  -- CONTENT JSONB
  content = jsonb_build_object(
    'title', TRIM(CONCAT(
      COALESCE(name, ''),
      CASE WHEN name_part_2 IS NOT NULL AND name_part_2 != '' THEN ' ' || name_part_2 ELSE '' END,
      CASE WHEN name_part_3 IS NOT NULL AND name_part_3 != '' THEN ' ' || name_part_3 ELSE '' END
    )),
    'description', description_text,
    'image', image,
    'button', jsonb_build_object(
      'text', button_text,
      'url', url,
      'is_text_link', COALESCE(is_text_link, true)
    )
  ),
  
  -- TRANSLATIONS JSONB
  translations = jsonb_build_object(
    'name', COALESCE(name_translation, '{}'::jsonb),
    'description', COALESCE(description_text_translation, '{}'::jsonb),
    'button_text', COALESCE(button_text_translation, '{}'::jsonb)
  ),
  
  -- STYLE JSONB
  style = jsonb_build_object(
    'background_color', COALESCE(background_color, 'white'),
    'title', jsonb_build_object(
      'color', NULL,
      'size', '3xl',
      'font', 'sans',
      'weight', 'bold'
    ),
    'description', jsonb_build_object(
      'color', NULL,
      'size', 'md',
      'font', 'sans',
      'weight', 'normal'
    ),
    'button', jsonb_build_object(
      'color', NULL,
      'text_color', 'white'
    ),
    'alignment', 'left',  -- Default value as requested
    'image_first', COALESCE(image_first, false),
    'image_style', 'default',  -- Default value
    'gradient', CASE 
      WHEN is_gradient = true THEN jsonb_build_object(
        'enabled', true,
        'config', COALESCE(gradient, '{}'::jsonb)
      )
      ELSE jsonb_build_object('enabled', false)
    END
  );

-- Step 4: Drop old columns (after verifying data migration)
-- IMPORTANT: Verify data is correctly migrated before running this step!
-- Uncomment the following lines after verification:

/*
ALTER TABLE public.website_templatesectionheading
DROP COLUMN IF EXISTS name,
DROP COLUMN IF EXISTS name_part_2,
DROP COLUMN IF EXISTS name_part_3,
DROP COLUMN IF EXISTS description_text,
DROP COLUMN IF EXISTS image,
DROP COLUMN IF EXISTS image_first,
DROP COLUMN IF EXISTS button_text,
DROP COLUMN IF EXISTS is_text_link,
DROP COLUMN IF EXISTS url,
DROP COLUMN IF EXISTS style_variant,
DROP COLUMN IF EXISTS text_style_variant,
DROP COLUMN IF EXISTS name_translation,
DROP COLUMN IF EXISTS description_text_translation,
DROP COLUMN IF EXISTS button_text_translation,
DROP COLUMN IF EXISTS background_color,
DROP COLUMN IF EXISTS is_gradient,
DROP COLUMN IF EXISTS gradient,
DROP COLUMN IF EXISTS is_included_template_sections_active;
*/

-- Step 5: Verify migration
-- Check a few records to ensure data was migrated correctly
SELECT 
  id,
  comment,
  url_page,
  content,
  translations,
  style
FROM public.website_templatesectionheading
LIMIT 5;

-- Step 6: Check structure comparison
SELECT 
  'Before Migration' as status,
  COUNT(*) as total_records,
  COUNT(CASE WHEN name IS NOT NULL THEN 1 END) as records_with_name,
  COUNT(CASE WHEN description_text IS NOT NULL THEN 1 END) as records_with_description
FROM website_templatesectionheading_backup

UNION ALL

SELECT 
  'After Migration' as status,
  COUNT(*) as total_records,
  COUNT(CASE WHEN content->>'title' IS NOT NULL THEN 1 END) as records_with_title,
  COUNT(CASE WHEN content->>'description' IS NOT NULL THEN 1 END) as records_with_description
FROM public.website_templatesectionheading;

-- Step 7: Final table structure (after dropping old columns)
-- This is what the table will look like after uncommenting Step 4:
/*
CREATE TABLE public.website_templatesectionheading (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment text DEFAULT 'for   ''  '' page',
  "order" bigint DEFAULT 0,
  url_page character varying(255),
  organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE,
  updated_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'),
  
  -- JSONB fields
  content jsonb DEFAULT '{}',
  translations jsonb DEFAULT '{}',
  style jsonb DEFAULT '{}'
);

-- Content structure:
{
  "title": "string",
  "description": "string",
  "image": "string",
  "button": {
    "text": "string",
    "url": "string",
    "is_text_link": boolean
  }
}

-- Translations structure:
{
  "name": {
    "en": "English title",
    "es": "Spanish title",
    ...
  },
  "description": {
    "en": "English description",
    ...
  },
  "button_text": {
    "en": "English button",
    ...
  }
}

-- Style structure:
{
  "background_color": "white",
  "title": {
    "color": null,
    "size": "3xl",      // xs | sm | md | lg | xl | 2xl | 3xl | 4xl
    "font": "sans",     // sans | serif | mono | display
    "weight": "bold"    // light | normal | medium | semibold | bold
  },
  "description": {
    "color": null,
    "size": "md",       // xs | sm | md | lg | xl
    "font": "sans",     // sans | serif | mono
    "weight": "normal"  // light | normal | medium | semibold
  },
  "button": {
    "color": null,      // defaults to primary_color in frontend
    "text_color": "white"
  },
  "alignment": "left",  // left | center | right
  "image_first": false,
  "image_style": "default",  // default | contained | full_width | circle
  "gradient": {
    "enabled": false,
    "config": {}
  }
}
*/

-- Indexes (recreate if needed)
DROP INDEX IF EXISTS idx_website_templatesectionheading_is_gradient;

-- Add indexes for JSONB queries if needed
CREATE INDEX IF NOT EXISTS idx_templatesectionheading_content ON public.website_templatesectionheading USING gin(content);
CREATE INDEX IF NOT EXISTS idx_templatesectionheading_style ON public.website_templatesectionheading USING gin(style);
CREATE INDEX IF NOT EXISTS idx_templatesectionheading_org_page ON public.website_templatesectionheading(organization_id, url_page);

-- Migration complete!
-- Next steps:
-- 1. Verify the data migration results above
-- 2. Test the application with new structure
-- 3. Once confirmed working, uncomment Step 4 to drop old columns
-- 4. Update TypeScript types and components
