-- Migration: Fix Model-Specific Settings
-- Date: 2025-11-05
-- Description: Separates default_settings per model, creates ai_model_settings table for per-user-per-model configurations

-- =====================================================
-- 1. Create new table for model-specific settings
-- =====================================================

CREATE TABLE IF NOT EXISTS public.ai_model_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL,
  model_id bigint NOT NULL,
  model_type text NOT NULL, -- 'default' or 'user'
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  
  CONSTRAINT ai_model_settings_pkey PRIMARY KEY (id),
  CONSTRAINT ai_model_settings_user_model_unique UNIQUE (user_id, model_id, model_type),
  CONSTRAINT ai_model_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles (id) ON DELETE CASCADE,
  CONSTRAINT ai_model_settings_model_type_check CHECK (model_type = ANY (ARRAY['default'::text, 'user'::text]))
) TABLESPACE pg_default;

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_ai_model_settings_user_id ON ai_model_settings(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_model_settings_model ON ai_model_settings(model_id, model_type);

-- =====================================================
-- 2. Create trigger to auto-update updated_at
-- =====================================================

CREATE OR REPLACE FUNCTION update_ai_model_settings_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_ai_model_settings_updated_at ON ai_model_settings;

CREATE TRIGGER set_ai_model_settings_updated_at
  BEFORE UPDATE ON ai_model_settings
  FOR EACH ROW
  EXECUTE FUNCTION update_ai_model_settings_updated_at();

-- =====================================================
-- 3. Migrate existing settings to new table
-- =====================================================

-- Migrate existing default_settings from ai_user_settings to ai_model_settings
-- Only migrate if there are actual settings and a model is selected
INSERT INTO ai_model_settings (user_id, model_id, model_type, settings)
SELECT 
  user_id,
  COALESCE(default_model_id, user_model_id) as model_id,
  COALESCE(selected_model_type, 'default') as model_type,
  default_settings
FROM ai_user_settings
WHERE default_settings IS NOT NULL 
  AND default_settings != '{}'::jsonb
  AND (default_model_id IS NOT NULL OR user_model_id IS NOT NULL)
ON CONFLICT (user_id, model_id, model_type) DO NOTHING;

-- =====================================================
-- 4. Update ai_user_settings table
-- =====================================================

-- Remove default_settings column from ai_user_settings (now stored per-model)
ALTER TABLE ai_user_settings 
DROP COLUMN IF EXISTS default_settings;

-- Add comment to clarify the table's new purpose
COMMENT ON TABLE ai_user_settings IS 'Stores user''s currently selected model and global files. Model-specific settings are now in ai_model_settings table.';
COMMENT ON TABLE ai_model_settings IS 'Stores model-specific settings for each user-model combination. Each user can have different settings for each AI model they use.';

-- =====================================================
-- Verification queries (run separately to check results)
-- =====================================================
-- Check migrated settings
-- SELECT user_id, model_id, model_type, settings FROM ai_model_settings LIMIT 10;

-- Check ai_user_settings structure
-- SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'ai_user_settings';

-- Count settings per user
-- SELECT user_id, COUNT(*) as model_settings_count FROM ai_model_settings GROUP BY user_id;
