'use client';

import { useEffect } from 'react';
import { pageMetadataDefinitions } from '@/lib/page-metadata-definitions';
import { usePathname } from 'next/navigation';

export default function MetadataComments() {
  const pathname = usePathname();

  useEffect(() => {
    const pageData = pageMetadataDefinitions[pathname];
    
    if (pageData && typeof document !== 'undefined') {
      // Create human-readable metadata comments
      const metadataComment = `
      
===============================================
PAGE METADATA - HUMAN READABLE FORMAT
===============================================
Current Page: ${pathname}
Page Title: ${pageData.title}
Description: ${pageData.description}
Keywords: ${pageData.keywords.join(', ')}
Generated from: /src/lib/page-metadata-definitions.ts
===============================================
SOCIAL MEDIA SHARING INFORMATION
===============================================
OpenGraph Title: ${pageData.openGraph?.title || pageData.title}
OpenGraph Description: ${pageData.openGraph?.description || pageData.description}
OpenGraph Type: ${pageData.openGraph?.type || 'website'}
Twitter Card: ${pageData.twitter?.card || 'summary_large_image'}
===============================================
SEO OPTIMIZATION DETAILS
===============================================
Robots Directive: ${pageData.robots || 'index, follow'}
Canonical URL: Will be dynamically generated
Meta Tags: Automatically generated by Next.js
===============================================
This page is optimized for:
• Search Engine Optimization (SEO)
• Social Media Sharing (Facebook, Twitter, LinkedIn)
• Web Crawlers and Search Bots
• Accessibility and User Experience
===============================================

      `;

      // Add comment to the document head
      const comment = document.createComment(metadataComment);
      document.head.appendChild(comment);

      // Add a data attribute to track metadata injection
      document.documentElement.setAttribute('data-metadata-injected', 'true');
      document.documentElement.setAttribute('data-page-path', pathname);
    }
  }, [pathname]);

  return null;
}
