export type BannerOpenState =
  | 'absent'
  | 'full'
  | 'left-half'
  | 'right-half'
  | 'top-half'
  | 'bottom-half'
  | 'left-30'
  | 'left-70'
  | 'right-30'
  | 'right-70'
  | 'top-30'
  | 'top-70'
  | 'bottom-30'
  | 'bottom-70';

export type BannerPosition = 'top' | 'bottom' | 'left' | 'right';

export interface BannerContent {
  text: string;
  icon?: string;
  link?: {
    url: string;
    label: string;
    isExternal?: boolean;
  };
  customContent?: string;
  banner_background?: string;
  banner_content_style?: string;
}

export interface Banner {
  id?: string; // Optional - will be generated by database as UUID
  created_at?: string;
  updated_at?: string;
  position: BannerPosition;
  type: 'permanent' | 'closed';
  is_enabled?: boolean; // Make optional for database compatibility
  is_active?: boolean; // Database field name
  content: BannerContent;
  open_state?: BannerOpenState; // Database field name
  openState?: BannerOpenState; // Frontend field name
  priority?: number;
  start_at?: string;
  end_at?: string;
  target_audience?: string;
  landing_content?: string;
  dismissal_duration?: string;
  comments?: string;
  page_paths?: string[] | null;
  organization_id?: string;
  is_fixed_above_navbar?: boolean; // Database field name
  isFixedAboveNavbar?: boolean; // Frontend field name
  end_date_promotion_is_displayed?: boolean;
  end_date_promotion?: string;
  // Computed/frontend fields
  isOpen?: boolean;
  isDismissed?: boolean;
}

// Deprecate BannerType in favor of Banner
export type BannerType = Banner;