name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: metexam-next-app-hagaefargkf6eqh8
  NODE_VERSION: '20.x'
  AZURE_RESOURCE_GROUP: <your-resource-group>  # Replace with your resource group name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      - name: Fetch Azure App Service environment variables
        run: |
          # Fetch app settings and export as environment variables
          az webapp config appsettings list \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --query "[].{name:name, value:value}" -o json | \
          jq -r '.[] | "export \(.name)=\(.value)"' >> $GITHUB_ENV
      - name: Debug environment variables
        run: |
          echo "SUPABASE_URL=$SUPABASE_URL"
          echo "NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL"
          echo "SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY"
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY"
          echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL"
          echo "NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL"
      - name: Install dependencies
        run: npm install
      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      - name: Build Next.js app
        run: npm run build
      - name: Prepare standalone folder
        run: |
          mv .next/static .next/standalone/.next/static
          cp -R public .next/standalone/public
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-app
          path: .next/standalone

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: next-app
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
