# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - metexam-next-app-2
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Debug environment variables
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_API_URL: ${{ secrets.NEXT_API_URL }}
          NEXT_PUBLIC_DOMAIN_CUSTOM: ${{ secrets.NEXT_PUBLIC_DOMAIN_CUSTOM }}
          NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_NAME }}
          NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_KEY }}
          NEXT_PUBLIC_AZURE_CONTAINER_NAME: ${{ secrets.NEXT_PUBLIC_AZURE_CONTAINER_NAME }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_PRICE_ID: ${{ secrets.STRIPE_PRICE_ID }}
          NEXT_PUBLIC_EMAIL_CONFIRM_REQUIRED: ${{ secrets.NEXT_PUBLIC_EMAIL_CONFIRM_REQUIRED }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: |
          echo "SUPABASE_URL is set: ${SUPABASE_URL:+true}"
          echo "SUPABASE_SERVICE_KEY is set: ${SUPABASE_SERVICE_KEY:+true}"
          echo "SUPABASE_SERVICE_ROLE_KEY is set: ${SUPABASE_SERVICE_ROLE_KEY:+true}"
          echo "NEXT_PUBLIC_SUPABASE_URL is set: ${NEXT_PUBLIC_SUPABASE_URL:+true}"
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY is set: ${NEXT_PUBLIC_SUPABASE_ANON_KEY:+true}"
          echo "NEXT_API_URL is set: ${NEXT_API_URL:+true}"
          echo "NEXT_PUBLIC_DOMAIN_CUSTOM is set: ${NEXT_PUBLIC_DOMAIN_CUSTOM:+true}"
          echo "NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_NAME is set: ${NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_NAME:+true}"
          echo "NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_KEY is set: ${NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_KEY:+true}"
          echo "NEXT_PUBLIC_AZURE_CONTAINER_NAME is set: ${NEXT_PUBLIC_AZURE_CONTAINER_NAME:+true}"
          echo "STRIPE_SECRET_KEY is set: ${STRIPE_SECRET_KEY:+true}"
          echo "STRIPE_PRICE_ID is set: ${STRIPE_PRICE_ID:+true}"
          echo "NEXT_PUBLIC_EMAIL_CONFIRM_REQUIRED is set: ${NEXT_PUBLIC_EMAIL_CONFIRM_REQUIRED:+true}"
          echo "NEXT_PUBLIC_API_URL is set: ${NEXT_PUBLIC_API_URL:+true}"
          echo "NEXT_PUBLIC_BASE_URL is set: ${NEXT_PUBLIC_BASE_URL:+true}"
          echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY is set: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:+true}"
          echo "NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME is set: ${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME:+true}"

      - name: npm install, build, and test
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_API_URL: ${{ secrets.NEXT_API_URL }}
          NEXT_PUBLIC_DOMAIN_CUSTOM: ${{ secrets.NEXT_PUBLIC_DOMAIN_CUSTOM }}
          NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_NAME }}
          NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_KEY }}
          NEXT_PUBLIC_AZURE_CONTAINER_NAME: ${{ secrets.NEXT_PUBLIC_AZURE_CONTAINER_NAME }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_PRICE_ID: ${{ secrets.STRIPE_PRICE_ID }}
          NEXT_PUBLIC_EMAIL_CONFIRM_REQUIRED: ${{ secrets.NEXT_PUBLIC_EMAIL_CONFIRM_REQUIRED }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
          NEXT_TELEMETRY_DISABLED: 1
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          
          
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r -x "node_modules/*" ".git/*" "tests/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_80B74F9A27134949BD239F137C210738 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_50F3C29154DC428B9794B02F5B97D138 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C6A3D9B2A5184D0BB4CD811E14B5CD8E }}

      - name: Check App Service deployment status
        continue-on-error: true
        run: |
          az webapp log deployment show --name metexam-next-app-2 --resource-group metexam-apps --output table
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C6A3D9B2A5184D0BB4CD811E14B5CD8E }}

      - name: Configure App Service settings
        run: |
          az webapp config appsettings set --name metexam-next-app-2 --resource-group metexam-apps --settings WEBSITES_PORT=3000 WEBSITE_NODE_DEFAULT_VERSION=20 SCM_DO_BUILD_DURING_DEPLOYMENT=true
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C6A3D9B2A5184D0BB4CD811E14B5CD8E }}

      - name: Wait for App Service settings to apply
        run: |
          echo "Waiting 60 seconds for App Service settings to apply..."
          sleep 60

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'metexam-next-app-2'
          package: .

      - name: Check App Service health
        run: |
          sleep 30
          curl -f https://metexam-next-app-2-frhqf5bjhkhxbhdg.uksouth-01.azurewebsites.net || exit 1
