name: Build and deploy Node.js app to Azure Web App - metexam-next-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Debug environment variables
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_API_URL: ${{ secrets.NEXT_API_URL }}
          NEXT_PUBLIC_DOMAIN_CUSTOM: ${{ secrets.NEXT_PUBLIC_DOMAIN_CUSTOM }}
          NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_NAME }}
          NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_KEY }}
          NEXT_PUBLIC_AZURE_CONTAINER_NAME: ${{ secrets.NEXT_PUBLIC_AZURE_CONTAINER_NAME }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_PRICE_ID: ${{ secrets.STRIPE_PRICE_ID }}
          NEXT_PUBLIC_EMAIL_CONFIRM_REQUIRED: ${{ secrets.NEXT_PUBLIC_EMAIL_CONFIRM_REQUIRED }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
        run: |
          echo "SUPABASE_URL is set: ${SUPABASE_URL:+true}"
          echo "SUPABASE_SERVICE_ROLE_KEY is set: ${SUPABASE_SERVICE_ROLE_KEY:+true}"
          echo "NEXT_PUBLIC_SUPABASE_URL is set: ${NEXT_PUBLIC_SUPABASE_URL:+true}"
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY is set: ${NEXT_PUBLIC_SUPABASE_ANON_KEY:+true}"
          echo "NEXT_API_URL is set: ${NEXT_API_URL:+true}"
          echo "NEXT_PUBLIC_DOMAIN_CUSTOM is set: ${NEXT_PUBLIC_DOMAIN_CUSTOM:+true}"
          echo "NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_NAME is set: ${NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_NAME:+true}"
          echo "NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_KEY is set: ${NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_KEY:+true}"
          echo "NEXT_PUBLIC_AZURE_CONTAINER_NAME is set: ${NEXT_PUBLIC_AZURE_CONTAINER_NAME:+true}"
          echo "STRIPE_SECRET_KEY is set: ${STRIPE_SECRET_KEY:+true}"
          echo "STRIPE_PRICE_ID is set: ${STRIPE_PRICE_ID:+true}"
          echo "NEXT_PUBLIC_EMAIL_CONFIRM_REQUIRED is set: ${NEXT_PUBLIC_EMAIL_CONFIRM_REQUIRED:+true}"
          echo "NEXT_PUBLIC_API_URL is set: ${NEXT_PUBLIC_API_URL:+true}"
          echo "NEXT_PUBLIC_BASE_URL is set: ${NEXT_PUBLIC_BASE_URL:+true}"
          echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY is set: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:+true}"

      - name: npm install, build, and test
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_API_URL: ${{ secrets.NEXT_API_URL }}
          NEXT_PUBLIC_DOMAIN_CUSTOM: ${{ secrets.NEXT_PUBLIC_DOMAIN_CUSTOM }}
          NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_NAME }}
          NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_KEY }}
          NEXT_PUBLIC_AZURE_CONTAINER_NAME: ${{ secrets.NEXT_PUBLIC_AZURE_CONTAINER_NAME }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_PRICE_ID: ${{ secrets.STRIPE_PRICE_ID }}
          NEXT_PUBLIC_EMAIL_CONFIRM_REQUIRED: ${{ secrets.NEXT_PUBLIC_EMAIL_CONFIRM_REQUIRED }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
          NEXT_TELEMETRY_DISABLED: 1
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1287D2EC5A5C4DFD8CCAEF0ABA240E8C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7BD85A785A0144F580B5D61E5E93E504 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1A59C40C6F1E435A9D15A571005CF4B1 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'metexam-next-app'
          slot-name: 'Production'
          package: .
